// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJzI5VwExfwUB6RcKiqa5etRrXzyTwxY8',
    appId: '1:751871598348:web:dd7ed509d0ba314d457329',
    messagingSenderId: '751871598348',
    projectId: 'ostello-fd492',
    authDomain: 'ostello-fd492.firebaseapp.com',
    storageBucket: 'ostello-fd492.firebasestorage.app',
    measurementId: 'G-FS3GPLMESC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjUcEpVnuLreBYSQu-rtRPT9UPYmOlSA',
    appId: '1:751871598348:android:b52a15fdc0ffd2fb457329',
    messagingSenderId: '751871598348',
    projectId: 'ostello-fd492',
    storageBucket: 'ostello-fd492.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_nr1vifJlfhgZ-Xm17kWqs0jrpgZzo_E',
    appId: '1:751871598348:ios:988faea5a11036e6457329',
    messagingSenderId: '751871598348',
    projectId: 'ostello-fd492',
    storageBucket: 'ostello-fd492.firebasestorage.app',
    iosBundleId: 'com.example.ostello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_nr1vifJlfhgZ-Xm17kWqs0jrpgZzo_E',
    appId: '1:751871598348:ios:988faea5a11036e6457329',
    messagingSenderId: '751871598348',
    projectId: 'ostello-fd492',
    storageBucket: 'ostello-fd492.firebasestorage.app',
    iosBundleId: 'com.example.ostello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJzI5VwExfwUB6RcKiqa5etRrXzyTwxY8',
    appId: '1:751871598348:web:badc32b732b36dd5457329',
    messagingSenderId: '751871598348',
    projectId: 'ostello-fd492',
    authDomain: 'ostello-fd492.firebaseapp.com',
    storageBucket: 'ostello-fd492.firebasestorage.app',
    measurementId: 'G-50H5071WK0',
  );
}
